const STORAGE_KEY="juegoDineroProgresoV2";
const FIREBASE_SETTINGS={enabled:false,config:{apiKey:"",authDomain:"",projectId:"",storageBucket:"",messagingSenderId:"",appId:""}};
let firebaseDb=null,firebaseApi=null,firebaseReady=false;
const worlds=[
{id:"cono-sur",region:"Cono Sur",name:"El Hogar",countries:["Panama","Costa Rica","Uruguay","Chile","Argentina","Paraguay","Brasil","Bolivia","Nicaragua","Guatemala"],description:"Finanzas del hogar, presupuesto, proteccion y decisiones familiares.",color:"#22D3EE",shape:"polygon(8% 28%,24% 8%,48% 14%,70% 4%,92% 24%,82% 54%,64% 62%,58% 92%,34% 80%,10% 70%)"},
{id:"andina",region:"Region Andina",name:"El Saber",countries:["Colombia","Ecuador","Peru","Venezuela","Quito","Medellin","Cali","Cuenca","Arequipa","Bogota"],description:"Educacion, deuda, reputacion crediticia, becas, divisas e inversion temprana.",color:"#D4AF37",shape:"polygon(18% 8%,44% 16%,66% 8%,86% 22%,74% 42%,88% 68%,56% 88%,36% 74%,12% 84%,22% 48%)"},
{id:"centroamerica",region:"Centroamerica",name:"Poder Femenino",countries:["El Salvador","Honduras","Belice","Guatemala Mujer","Panama Mujer","Costa Rica Mujer","Nicaragua Mujer","San Salvador","Tegucigalpa","Managua"],description:"Riesgo, salario, patrimonio y emprendimiento con foco en mujeres.",color:"#FF00FF",shape:"polygon(6% 44%,20% 26%,44% 30%,58% 14%,90% 26%,76% 48%,94% 72%,58% 86%,38% 68%,12% 76%)"},
{id:"caribe",region:"Caribe",name:"El Mercado",countries:["Republica Dominicana","Puerto Rico","Cuba","Jamaica","Trinidad","Barbados","Haiti","Bahamas","Curazao","Aruba"],description:"Consumo responsable, economia circular, inflacion, crisis y etica.",color:"#50C878",shape:"polygon(12% 20%,38% 8%,58% 24%,84% 18%,94% 48%,74% 64%,68% 90%,42% 76%,18% 88%,6% 56%)"},
{id:"norte-latino",region:"Norteamerica Latina",name:"El Futuro",countries:["Mexico","Monterrey","Guadalajara","CDMX","Puebla","Merida","Tijuana","Queretaro","Leon","Cancun"],description:"Jubilacion, banca, fintech, cripto, hipotecas e inversion.",color:"#FFBF00",shape:"polygon(10% 16%,42% 6%,74% 18%,88% 40%,78% 70%,54% 86%,28% 76%,14% 92%,6% 62%,22% 42%)"}];
const topics=["Finanzas del hogar y roles familiares","Elaboracion y gestion de presupuestos","Estrategias de ahorro y reduccion de costos","Eventos familiares","Costos reales de mascotas","Impacto economico por perdida de proveedor","Mecanismos para paliar: seguros","Gestion de deudas","Planificacion patrimonial","Tecnologia y organizacion financiera","Costo y valor de educacion","Conceptos basicos de deuda","Reputacion crediticia","Herramientas de planificacion","Valor del titulo vs precio educativo","Becas y financiamiento","Estudiar en extranjero","Cuentas internacionales","Sistema fiscal","Inversion temprana","Educacion financiera como motor profesional","Negociacion salarial","Del salario al patrimonio","Seguros esenciales","Analisis de riesgos","Seguros de salud e incapacidad","Quiebra y reestructuracion","Diversificacion de ingresos","Emprendimiento y riesgos","Planificacion fiscal","Consumo responsable","Economia circular","Fast fashion","Historia economica","Tendencias futuras","Inflacion y deflacion","Educacion financiera para mujeres","Politicas monetarias y fiscales","Inversion etica","Finanzas en crisis","Planes de pension","Seguridad social global","Hipotecas","Organismos de proteccion","Finanzas 1.0 vs 4.0","Fintech y regulacion","Criptomonedas","Metaverso y activos digitales","Bancarizacion basica","Inversion a largo plazo"];
const levels={1:{name:"Nino",duration:45,intro:"misiones cortas con companeros que reaccionan"},2:{name:"Adolescente",duration:60,intro:"retos con apps, redes, salidas y dinero propio"},3:{name:"Mujer adulta",duration:90,intro:"autonomia, patrimonio, tecnologia y emprendimiento femenino"},4:{name:"Estudiante emprendedor",duration:120,intro:"startup, universidad, caja y mercados volatiles"}};
const child=[["Eliseo","Huron","#22D3EE","ferret","sable"],["Louise","Huron","#DC143C","ferret","dark"],["Baco","Huron","#FFBF00","ferret","gold"],["Athenea","Huron","#9400D3","ferret","silver"],["Gaia","Huron","#50C878","ferret","cream"],["Elsa","Huron","#E0FFFF","ferret","white"],["Lau","Setter ingles","#D4AF37","setter","white-gold"],["Julio","Mestizo de mastin","#0047AB","mastiff","brown"],["Boston","Gata con manchas marrones y negras","#FF00FF","cat","calico"],["Penelope","Gata totalmente blanca","#F3F4F6","cat","white"]].map(c=>char(c,"guia interactivo"));
const teen=[["Vale Byte","Creadora digital","#FF00FF","human"],["Nico Flow","Productor urbano","#00FF00","human"],["Danna Trend","Curadora de estilo","#FFD1DC","human"],["Leo Gamer","Estratega gamer","#22D3EE","human"],["Maya Data","Analista joven","#D4AF37","human"],["Thiago Fix","Maker","#50C878","human"]].map(c=>char(c,"reto adolescente"));
const woman=[["Ari Tech","Mujer tech","#00FF00","human"],["Sofia Capital","Inversionista","#D4AF37","human"],["Luna Pitch","Emprendedora","#FF00FF","human"],["Noa Legal","Mentora legal","#E0FFFF","human"],["Iris Mercado","Estratega comercial","#50C878","human"]].map(c=>char(c,"mentora mujer"));
const entrepreneur=[["Kai Venture","Fundador estudiante","#FFBF00","human"],["Rafa Bolsa","Analista de mercado","#22D3EE","human"],["Mila CFO","Directora financiera","#D4AF37","human"],["Tomas Scale","Operador de crecimiento","#0047AB","human"],["Zoe Lab","Innovadora fintech","#9400D3","human"]].map(c=>char(c,"mentor emprendedor"));
function char(c,role){return{name:c[0],species:c[1],color:c[2],kind:c[3],coat:c[4]||"",role,tone:"te propone una situacion real para probar tu presupuesto"}}
const pools={1:child,2:teen,3:woman,4:entrepreneur};
const surprises={1:["Se rompe un cargador y cuesta $18.","La merienda sube $1 por dia.","Piden $12 para una salida escolar.","La mascota necesita comida antes de tiempo.","Hay oferta de juguete pero falta ahorro."],2:["Tres apps cobran suscripcion el mismo dia.","La salida cuesta el doble de lo acordado.","Se rompe el celular y cuesta $45.","Una tienda lanza descuento relampago.","Ofrecen compra ahora y paga despues."],3:["Un gasto medico consume parte del fondo.","Un cliente retrasa pago a tu emprendimiento.","La tarjeta sube la tasa.","Una inversion cae 12% en una semana.","Un curso compite con el fondo de emergencia."],4:["La bolsa cae 15%.","El proveedor sube precios por divisa.","Un cliente paga 30 dias tarde.","La campana vende pero falta inventario.","Una regulacion exige invertir en seguridad."]};
const positions=[[[6,18],[24,8],[46,17],[70,9],[83,29],[70,50],[48,43],[24,61],[10,42],[42,75]],[[18,9],[38,18],[60,10],[80,28],[66,45],[84,66],[58,82],[36,68],[16,80],[28,44]],[[8,45],[20,26],[44,30],[58,14],[82,28],[74,48],[90,70],[58,84],[38,66],[14,74]],[[12,20],[38,10],[58,24],[82,18],[90,48],[72,63],[65,84],[42,74],[20,86],[8,56]],[[10,18],[40,8],[72,20],[85,40],[76,68],[54,84],[30,74],[14,88],[8,61],[24,42]]];
let state=loadState(),selectedWorld=0,selectedLevel=state.level||1,onboardingLevel=selectedLevel,activeMission=null,activeQuestion=0,activeAnswers=[];
const modules=topics.map((topic,i)=>({id:i+1,code:`M${i+1}`,topic,worldIndex:Math.floor(i/10),localIndex:i%10,country:worlds[Math.floor(i/10)].countries[i%10],activities:Array.from({length:5},(_,a)=>activity(i,a))}));
function activity(i,a){const options=[["Pausar, medir impacto y ajustar una categoria","Comprar por impulso","Ignorar el gasto","Usar deuda sin revisar"],["Comparar costo total, plazo y riesgo","Elegir cuota baja sin leer","Pagar tarde","Usar credito sin presupuesto"],["Revisar ingreso neto, obligaciones y reserva","Preguntar solo a amistades","Mirar precio llamativo","Creer ganancia rapida"],["Separar cuentas y documentar decisiones","Depender de una fuente","No hablar de dinero","Aceptar precio sin calcular"],["Definir regla, medir y reponer reserva","Esperar a tener mucho","Copiar otro pais","Invertir sin emergencia"]][a];const rot=options.slice(a%4).concat(options.slice(0,a%4));return{name:["Quiz aplicado","Simulacion","Calculo guiado","Caso latinoamericano","Plan de accion"][a]+": "+topics[i],question:["Que accion demuestra mejor dominio ante el imprevisto?","Que decision protege mejor el avance financiero?","Que dato revisas primero?","Que practica aumenta autonomia y control?","Que respuesta crea un plan real?"][a],options:rot.map(x=>({text:x,isCorrect:x===options[0]})),capsule:`Conecta ${topics[i].toLowerCase()} con precio, plazo, riesgo, ingreso y liquidez.`,tip:["Efectivo y billeteras digitales conviven en Latinoamerica.","Comparar en dolares ayuda, pero cada pais tiene costos propios.","Separar dinero personal y de negocio evita caos.","La inflacion exige revisar precios cada mes.","La autonomia financiera requiere historial y decisiones documentadas."][(i+a)%5]}};
function loadState(){const f={playerName:"",studentId:"",createdAt:"",updatedAt:"",tokens:0,level:1,unlocked:1,completed:{},scores:{},attempts:[]};try{if(location.search.includes("reset=1")){localStorage.removeItem(STORAGE_KEY);return f}return{...f,...JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}")}}catch{return f}}
function saveState(){state.updatedAt=new Date().toISOString();try{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}catch{}}
async function initFirebase(){const ext=window.JUEGO_DINERO_FIREBASE||{};const settings={...FIREBASE_SETTINGS,...ext,config:{...FIREBASE_SETTINGS.config,...(ext.config||{})}};if(!settings.enabled||!settings.config.projectId)return;try{const appM=await import("https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js");const fireM=await import("https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js");firebaseDb=fireM.getFirestore(appM.initializeApp(settings.config));firebaseApi=fireM;firebaseReady=true;renderFirebaseStatus()}catch(e){console.warn("Firebase no pudo iniciar",e);renderFirebaseStatus("Firebase no pudo iniciar")}}
function init(){document.body.dataset.level=selectedLevel;initFirebase();setupOnboarding();renderCompanions();document.getElementById("name-form").addEventListener("submit",e=>{e.preventDefault();const name=document.getElementById("player-name").value.trim();if(!name)return;state.playerName=name;if(!state.studentId)state.studentId=`STD-${Date.now()}-${Math.random().toString(36).slice(2,8).toUpperCase()}`;if(!state.createdAt)state.createdAt=new Date().toISOString();selectedLevel=onboardingLevel;state.level=selectedLevel;document.body.dataset.level=selectedLevel;saveState();showGame()});document.querySelectorAll(".levels button").forEach(b=>b.onclick=()=>{selectedLevel=+b.dataset.level;state.level=selectedLevel;document.body.dataset.level=selectedLevel;saveState();render()});document.getElementById("close-mission").onclick=()=>document.getElementById("mission").close();document.getElementById("close-certificate").onclick=()=>document.getElementById("certificate").close();document.getElementById("export-json").onclick=()=>downloadData("json");document.getElementById("export-csv").onclick=()=>downloadData("csv");if(state.playerName)showGame();particles()}
function setupOnboarding(){document.querySelectorAll("[data-onboard-level]").forEach(b=>{b.classList.toggle("active",+b.dataset.onboardLevel===onboardingLevel);b.onclick=()=>{onboardingLevel=+b.dataset.onboardLevel;selectedLevel=onboardingLevel;document.body.dataset.level=selectedLevel;setupOnboarding();renderCompanions()}})}
function pair(w,l){const p=pools[l];return l===1?[p[w*2],p[w*2+1]]:[p[(w*2)%p.length],p[(w*2+1)%p.length]]}
function guide(m){return pair(m.worldIndex,selectedLevel)[m.localIndex%2]}
function renderCompanions(){const p=pair(0,onboardingLevel);document.getElementById("companions").innerHTML=`<div class="mini">${avatar(p[0])}</div><div class="mini">${avatar(p[1])}</div><div class="copy"><b>${p[0].name} y ${p[1].name} abren tu ruta</b><span>${levels[onboardingLevel].intro}. Cada reto trae un imprevisto.</span></div>`}
function showGame(){document.getElementById("onboarding").classList.add("hidden");document.getElementById("game").classList.remove("hidden");render()}
function render(){if(!state.playerName)return;document.getElementById("welcome").textContent=`Hola, ${state.playerName}`;document.getElementById("tokens").textContent=state.tokens;document.getElementById("done").textContent=`${Object.keys(state.completed).length}/50`;const vals=Object.values(state.scores);document.getElementById("score").textContent=(vals.length?vals[vals.length-1]:0)+"%";document.querySelectorAll(".levels button").forEach(b=>b.classList.toggle("active",+b.dataset.level===selectedLevel));renderFirebaseStatus();renderWorlds();renderMap()}
function renderFirebaseStatus(msg){const s=document.getElementById("firebase-status");if(!s)return;if(firebaseReady){s.className="firebase-status online";s.textContent="Firebase activo: los intentos se guardan en Firestore"}else{s.className="firebase-status local";s.textContent=msg||"Guardado local activo: pega tu firebaseConfig para activar Firestore"}}
function renderWorlds(){const box=document.getElementById("world-buttons");box.innerHTML="";worlds.forEach((w,i)=>{const done=modules.filter(m=>m.worldIndex===i&&state.completed[m.id]).length,p=pair(i,selectedLevel),b=document.createElement("button");b.className=i===selectedWorld?"active":"";b.innerHTML=`<strong>${w.region}: ${w.name}</strong><small>${p[0].name} + ${p[1].name} · ${done}/10 paises</small>`;b.onclick=()=>{selectedWorld=i;render()};box.appendChild(b);if(done===10){const c=document.createElement("button");c.textContent=`Emitir certificado: ${w.name}`;c.onclick=()=>openCertificate(i);box.appendChild(c)}})}
function renderMap(){const w=worlds[selectedWorld],p=pair(selectedWorld,selectedLevel);document.getElementById("world-region").textContent=w.region;document.getElementById("world-title").textContent=w.name;document.getElementById("world-description").textContent=`${w.description} Guias activos: ${p[0].name} y ${p[1].name}.`;const map=document.getElementById("map");map.innerHTML=`<div class="continent" style="--world-color:${w.color};clip-path:${w.shape}"></div>`;const pos=positions[selectedWorld],mods=modules.filter(m=>m.worldIndex===selectedWorld);pos.slice(0,-1).forEach((a,i)=>route(map,a,pos[i+1]));mods.forEach((m,i)=>{const g=guide(m),b=document.createElement("button"),[l,t]=pos[i];b.className=`node ${state.completed[m.id]?"done":""}`;b.style.left=l+"%";b.style.top=t+"%";b.style.borderColor=m.id<=state.unlocked?w.color:"";b.disabled=m.id>state.unlocked;b.innerHTML=`<b>${m.code}</b><small>${m.country}</small><em>${g.name}</em>`;b.onclick=()=>openMission(m);map.appendChild(b)})}
function route(map,a,b){const line=document.createElement("span"),dx=b[0]-a[0],dy=b[1]-a[1],len=Math.sqrt(dx*dx+dy*dy),ang=Math.atan2(dy,dx)*180/Math.PI;line.className="route";line.style.left=`calc(${a[0]}% + 43px)`;line.style.top=`calc(${a[1]}% + 43px)`;line.style.width=len+"%";line.style.transform=`rotate(${ang}deg)`;map.appendChild(line)}
function openMission(m){activeMission=m;activeQuestion=0;activeAnswers=[];renderMission();openDialog(document.getElementById("mission"))}
function renderMission(){const a=activeMission.activities[activeQuestion],g=guide(activeMission),p=pair(activeMission.worldIndex,selectedLevel),support=p.find(x=>x.name!==g.name)||p[0],sur=surprises[selectedLevel][(activeMission.id+activeQuestion)%5];document.getElementById("mission-content").innerHTML=`<div class="mission-body"><div class="pill-row"><span class="pill">${activeMission.code}</span><span class="pill">${activeMission.country}</span><span class="pill">${levels[selectedLevel].name}</span><span class="pill">${levels[selectedLevel].duration} min</span></div><div class="mission-grid"><aside class="card"><div class="guide-duo">${mini(g)}${mini(support)}</div><div class="interaction"><b>${g.name}</b> plantea la mision. <b>${support.name}</b> cambia el escenario si respondes sin pensar.</div></aside><section><div class="capsule"><p class="brand-p">Capsula ${activeQuestion+1}/5</p><h3>${a.name}</h3><p>${a.capsule}</p><p>${a.tip}</p></div><div class="surprise"><p>Imprevisto del dia</p><h3>${sur}</h3><p>Responde como si acabara de pasar.</p></div><div class="card"><h3>${a.question}</h3><div class="options">${a.options.map((o,i)=>`<button data-option="${i}" class="${activeAnswers[activeQuestion]===i?"selected":""}">${o.text}</button>`).join("")}</div></div><div class="actions"><button class="secondary" id="prev" ${activeQuestion===0?"disabled":""}>Anterior</button><button id="next" ${activeAnswers[activeQuestion]===undefined?"disabled":""}>${activeQuestion===4?"Calificar":"Siguiente"}</button></div></section></div></div>`;document.querySelectorAll("[data-option]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-option]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");activeAnswers[activeQuestion]=+b.dataset.option;document.getElementById("next").disabled=false});document.getElementById("prev").onclick=()=>{if(activeQuestion>0){activeQuestion--;renderMission()}};document.getElementById("next").onclick=()=>{activeQuestion<4?(activeQuestion++,renderMission()):grade()}}
function mini(c){return`<div class="guide"><div class="avatar">${avatar(c)}</div><h3>${c.name}</h3><p>${c.species}</p></div>`}
function grade(){const correct=activeMission.activities.reduce((s,a,i)=>s+(a.options[activeAnswers[i]]?.isCorrect?1:0),0),score=Math.round(correct/5*100),passed=score>=80,g=guide(activeMission);if(passed){if(!state.completed[activeMission.id])state.tokens+=100+(score===100?50:25);state.completed[activeMission.id]=true;state.unlocked=Math.max(state.unlocked,activeMission.id+1)}state.scores[activeMission.id]=score;recordAttempt(correct,score,passed);saveState();syncAttemptIfConfigured();document.getElementById("mission-content").innerHTML=`<div class="mission-body"><div class="result"><p>Resultado</p><h2 class="${passed?"ok":"bad"}">${score}%</h2><p>${passed?`${g.name} desbloqueo el siguiente pais.`:`${g.name} recomienda repetir. Necesitas 80%.`}</p><div class="pill-row"><span class="pill">${correct}/5 correctas</span><span class="pill">${state.tokens} tokens</span><span class="pill">${Object.keys(state.completed).length}/50 paises</span></div><button id="finish">Volver al mapa</button></div></div>`;document.getElementById("finish").onclick=()=>{document.getElementById("mission").close();render();if(passed&&modules.filter(m=>m.worldIndex===activeMission.worldIndex).every(m=>state.completed[m.id]))openCertificate(activeMission.worldIndex)}}
function recordAttempt(correct,score,passed){const m=activeMission,w=worlds[m.worldIndex],g=guide(m);const attempt={attemptId:`${state.studentId||"student"}-${Date.now()}`,studentId:state.studentId,studentName:state.playerName,level:selectedLevel,levelName:levels[selectedLevel].name,worldId:w.id,worldName:`${w.region}: ${w.name}`,moduleId:m.id,moduleCode:m.code,moduleTopic:m.topic,country:m.country,guide:g.name,correct,total:5,score,passed,tokensAfterAttempt:state.tokens,completedModules:Object.keys(state.completed).length,answers:activeAnswers.slice(),answerDetails:m.activities.map((a,i)=>({question:a.question,selectedOption:a.options[activeAnswers[i]]?.text||"",correct:Boolean(a.options[activeAnswers[i]]?.isCorrect)})),createdAt:new Date().toISOString()};state.attempts=Array.isArray(state.attempts)?state.attempts:[];state.attempts.push(attempt)}
function dataset(){return{student:{id:state.studentId,name:state.playerName,selectedLevel,selectedLevelName:levels[selectedLevel].name,createdAt:state.createdAt,updatedAt:state.updatedAt},progress:{tokens:state.tokens,unlocked:state.unlocked,completedModules:Object.keys(state.completed).length,completed:state.completed,scores:state.scores},attempts:state.attempts||[]}}
function downloadData(format){const data=dataset(),safe=(state.playerName||"estudiante").replace(/[^a-z0-9_-]+/gi,"_");if(format==="csv"){const h=["attemptId","studentId","studentName","level","levelName","worldName","moduleCode","moduleTopic","country","guide","correct","total","score","passed","tokensAfterAttempt","completedModules","createdAt"],rows=[h.join(",")];(data.attempts||[]).forEach(a=>rows.push(h.map(k=>`"${String(a[k]??"").replace(/"/g,'""')}"`).join(",")));file(`datos_${safe}.csv`,"text/csv",rows.join("\n"))}else file(`datos_${safe}.json`,"application/json",JSON.stringify(data,null,2))}
function file(name,type,content){const blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();URL.revokeObjectURL(url)}
function syncAttemptIfConfigured(){syncFirebase()}
async function syncFirebase(){if(!firebaseDb||!firebaseApi||!navigator.onLine||!state.attempts.length)return;const last=state.attempts[state.attempts.length-1],data=dataset();try{const ref=firebaseApi.doc(firebaseDb,"students",state.studentId);await firebaseApi.setDoc(ref,{...data.student,progress:data.progress,lastScore:last.score,lastWorld:last.worldName,lastModule:last.moduleCode,lastAttemptAt:last.createdAt,updatedAt:new Date().toISOString()},{merge:true});await firebaseApi.addDoc(firebaseApi.collection(firebaseDb,"students",state.studentId,"attempts"),last);renderFirebaseStatus()}catch(e){console.warn("No se pudo guardar en Firebase",e);renderFirebaseStatus("No se pudo guardar en Firebase; quedo local")}}
function openCertificate(i){const w=worlds[i],done=modules.filter(m=>m.worldIndex===i&&state.completed[m.id]).length,date=new Date().toLocaleDateString("es-ES",{year:"numeric",month:"long",day:"numeric"});document.getElementById("certificate-content").innerHTML=`<div class="mission-body"><section class="certificate"><p>Certificado de aprobacion</p><h2>El Juego del Dinero</h2><p>Otorga el presente certificado a</p><div class="cert-name">${state.playerName}</div><p>por aprobar</p><h3>${w.region}: ${w.name}</h3><p>${w.description}</p><div class="pill-row"><span class="pill">${done}/10 paises aprobados</span><span class="pill">Nota minima: 80%</span><span class="pill">${date}</span></div></section><div class="actions"><button class="secondary" id="close-cert-action">Volver</button><button id="print-cert">Imprimir o guardar PDF</button></div></div>`;document.getElementById("close-cert-action").onclick=()=>document.getElementById("certificate").close();document.getElementById("print-cert").onclick=()=>print();openDialog(document.getElementById("certificate"))}
function openDialog(d){d.showModal?d.showModal():d.setAttribute("open","open")}
function avatar(c){if(c.kind==="ferret")return ferret(c);if(c.kind==="setter"||c.kind==="mastiff")return dog(c);if(c.kind==="cat")return cat(c);return human(c)}
function ferret(c){const coats={sable:["#8B5A2B","#F3D7B6"],dark:["#3B2417","#C6A27A"],gold:["#B8860B","#FFE5A3"],silver:["#BFC7D5","#F3F4F6"],cream:["#E8D5AD","#FFF4CC"],white:["#F8FAFC","#DCEBFF"]},[b,f]=coats[c.coat]||coats.sable;return`<svg viewBox="0 0 140 140"><ellipse cx="72" cy="76" rx="44" ry="34" fill="${b}" stroke="${c.color}" stroke-width="4"/><ellipse cx="70" cy="72" rx="25" ry="20" fill="${f}"/><path d="M34 52c-12-6-18-1-20 9M106 52c12-6 18-1 20 9" stroke="${b}" stroke-width="10" stroke-linecap="round"/><circle cx="58" cy="68" r="4" fill="#020617"/><circle cx="82" cy="68" r="4" fill="#020617"/><path d="M67 79h8M71 79v8" stroke="#020617" stroke-width="3"/></svg>`}
function dog(c){const set=c.kind==="setter",base=set?"#F8FAFC":"#8A5A3C",spot=set?"#D4AF37":"#4A2D1F",ear=set?"#B8860B":"#2A160D";return`<svg viewBox="0 0 140 140"><ellipse cx="70" cy="72" rx="${set?36:42}" ry="${set?38:34}" fill="${base}" stroke="${c.color}" stroke-width="4"/><path d="M38 48c-18 8-20 34-10 48M102 48c18 8 20 34 10 48" stroke="${ear}" stroke-width="${set?13:18}" stroke-linecap="round" fill="none"/><path d="M54 42c9 8 20 8 32 0" stroke="${spot}" stroke-width="10" stroke-linecap="round"/><circle cx="56" cy="68" r="5" fill="#020617"/><circle cx="84" cy="68" r="5" fill="#020617"/></svg>`}
function cat(c){const white=c.coat==="white",base=white?"#F8FAFC":"#F3D7B6";return`<svg viewBox="0 0 140 140"><path d="M40 48 28 20l30 16M100 48l12-28-30 16" fill="${base}" stroke="${c.color}" stroke-width="4"/><circle cx="70" cy="70" r="40" fill="${base}" stroke="${c.color}" stroke-width="4"/>${white?"":`<path d="M44 47c10-12 25-13 34-4 10 9 25 5 32-4v42c-16-8-26-2-34 6-10 9-24 4-32-4z" fill="#4B2A16"/><circle cx="90" cy="56" r="13" fill="#111827"/>`}<circle cx="56" cy="68" r="5" fill="#020617"/><circle cx="84" cy="68" r="5" fill="#020617"/></svg>`}
function human(c){return`<svg viewBox="0 0 140 140"><circle cx="70" cy="42" r="22" fill="${c.species.includes("Mujer")?"#FFD1DC":"#E0FFFF"}" stroke="${c.color}" stroke-width="4"/><path d="M32 118c6-29 21-48 38-48s32 19 38 48" fill="${c.color}" opacity=".28" stroke="${c.color}" stroke-width="4"/><path d="M49 44h42M54 56c10 8 22 8 32 0" stroke="#020617" stroke-width="4" fill="none"/><path d="M34 98h72" stroke="#D4AF37" stroke-width="5"/></svg>`}
function particles(){const c=document.getElementById("particles"),x=c.getContext("2d"),ps=Array.from({length:70},(_,i)=>({x:Math.random(),y:Math.random(),s:10+Math.random()*18,v:.00025+Math.random()*.00045,d:(Math.random()-.5)*.00028,t:i%3}));function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio}function frame(){x.clearRect(0,0,c.width,c.height);ps.forEach(p=>{p.y-=p.v;p.x+=p.d;if(p.y<-.08)p.y=1.08;if(p.x<-.08)p.x=1.08;if(p.x>1.08)p.x=-.08;const X=p.x*c.width,Y=p.y*c.height,S=p.s*devicePixelRatio;x.save();if(p.t===0){x.translate(X,Y);x.rotate(Math.sin(Date.now()/1600+X)*.25);x.strokeStyle="rgba(80,200,120,.46)";x.fillStyle="rgba(80,200,120,.08)";x.strokeRect(-S*.8,-S*.42,S*1.6,S*.84);x.fillRect(-S*.8,-S*.42,S*1.6,S*.84);x.fillStyle="rgba(224,255,255,.68)";x.font=`${S*.7}px Arial`;x.textAlign="center";x.textBaseline="middle";x.fillText("$",0,1)}else if(p.t===1){x.strokeStyle="rgba(212,175,55,.62)";x.fillStyle="rgba(212,175,55,.12)";x.beginPath();x.arc(X,Y,S*.48,0,Math.PI*2);x.fill();x.stroke();x.fillStyle="rgba(255,191,0,.72)";x.font=`${S*.6}px Arial`;x.textAlign="center";x.textBaseline="middle";x.fillText("$",X,Y+1)}else{x.strokeStyle="rgba(34,211,238,.46)";x.lineWidth=2;x.beginPath();x.moveTo(X-S,Y+S*.4);x.lineTo(X-S*.35,Y);x.lineTo(X+S*.1,Y+S*.22);x.lineTo(X+S,Y-S*.5);x.stroke()}x.restore()});requestAnimationFrame(frame)}addEventListener("resize",resize);resize();frame()}
try{init()}catch(e){document.body.innerHTML=`<main class="shell"><section class="panel"><h1>No se pudo cargar</h1><p>${String(e.message||e)}</p></section></main>`}
